--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-07-25 12:56:53

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 24583)
-- Name: pet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pet (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    weight numeric NOT NULL,
    vaccination_status boolean NOT NULL,
    training_level integer NOT NULL,
    breed_id bigint NOT NULL
);


ALTER TABLE public.pet OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 24596)
-- Name: Pet_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Pet_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 50
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 24578)
-- Name: breed; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.breed (
    id bigint NOT NULL,
    name character varying(50)
);


ALTER TABLE public.breed OWNER TO postgres;

--
-- TOC entry 4841 (class 0 OID 24578)
-- Dependencies: 215
-- Data for Name: breed; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.breed (id, name) FROM stdin;
1	poodle
2	bulldog
3	beagle
\.


--
-- TOC entry 4842 (class 0 OID 24583)
-- Dependencies: 216
-- Data for Name: pet; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pet (id, name, weight, vaccination_status, training_level, breed_id) FROM stdin;
3	laika	7	t	1	2
4	roco	10	t	6	3
1	kefka	15	f	2	1
2	lola	5	t	4	1
\.


--
-- TOC entry 4852 (class 0 OID 0)
-- Dependencies: 217
-- Name: Pet_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Pet_ID_seq"', 2, true);


--
-- TOC entry 4694 (class 2606 OID 24582)
-- Name: breed Breed_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.breed
    ADD CONSTRAINT "Breed_pkey" PRIMARY KEY (id);


--
-- TOC entry 4696 (class 2606 OID 24589)
-- Name: pet Pet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pet
    ADD CONSTRAINT "Pet_pkey" PRIMARY KEY (id);


--
-- TOC entry 4697 (class 2606 OID 24590)
-- Name: pet BreedFK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pet
    ADD CONSTRAINT "BreedFK" FOREIGN KEY (breed_id) REFERENCES public.breed(id);


--
-- TOC entry 4849 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO admin;


--
-- TOC entry 4850 (class 0 OID 0)
-- Dependencies: 216
-- Name: TABLE pet; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.pet TO admin;


--
-- TOC entry 4851 (class 0 OID 0)
-- Dependencies: 215
-- Name: TABLE breed; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.breed TO admin;


--
-- TOC entry 2042 (class 826 OID 24597)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO admin;


-- Completed on 2024-07-25 12:56:53

--
-- PostgreSQL database dump complete
--

